apiVersion: v1
kind: Service
metadata:
  name: ${image_name}
  namespace: ${k8s_namespace}
  labels:
    app: ${image_name}
spec:
  type: NodePort
  selector:
    app: ${image_name}
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: ${k8s_node_port}
