apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${image_name}
  namespace: ${k8s_namespace}
  labels:
    app: ${image_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${image_name}
  template:
    metadata:
      labels:
        app: ${image_name}
    spec:
      containers:
        - name: ${image_name}
          image: ${registry_address}/${image_name}:init
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
